"""baseline

Revision ID: c5dffad43956
Revises: 
Create Date: 2026-07-13 02:24:34.865563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5dffad43956'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_comuna', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=False),
    sa.Column('ola_calor_score', sa.Float(), nullable=False),
    sa.Column('ola_frio_score', sa.Float(), nullable=False),
    sa.Column('viento_score', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_climate_comuna_time', 'climate_readings', ['cod_comuna', 'measured_at'], unique=False)
    op.create_table('daily_risk_scores',
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('cod_comuna', sa.Integer(), nullable=False),
    sa.Column('sismo_score', sa.Float(), nullable=False),
    sa.Column('ola_calor_score', sa.Float(), nullable=False),
    sa.Column('ola_frio_score', sa.Float(), nullable=False),
    sa.Column('viento_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('dominant_hazard', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('score_date', 'cod_comuna')
    )
    op.create_table('regions',
    sa.Column('codregion', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('area_km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('codregion')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_comuna', sa.Integer(), nullable=False),
    sa.Column('sismo_score', sa.Float(), nullable=False),
    sa.Column('ola_calor_score', sa.Float(), nullable=False),
    sa.Column('ola_frio_score', sa.Float(), nullable=False),
    sa.Column('viento_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('dominant_hazard', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_comuna_time', 'risk_scores', ['cod_comuna', 'computed_at'], unique=False)
    op.create_index('idx_risk_severity', 'risk_scores', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_scores_cod_comuna'), 'risk_scores', ['cod_comuna'], unique=False)
    op.create_table('seismic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('depth_km', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_at_local', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_source', 'seismic_events', ['source'], unique=False)
    op.create_index('idx_event_time', 'seismic_events', ['occurred_at'], unique=False)
    op.create_table('seismic_impacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('cod_comuna', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_intensity', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impact_comuna', 'seismic_impacts', ['cod_comuna'], unique=False)
    op.create_index('idx_impact_event', 'seismic_impacts', ['event_id'], unique=False)
    op.create_index('idx_impact_event_comuna', 'seismic_impacts', ['event_id', 'cod_comuna'], unique=True)
    op.create_table('senapred_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('senapred_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url_access', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_monitor', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('senapred_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(length=128), nullable=True),
    sa.Column('affected_scope', sa.String(length=16), nullable=False),
    sa.Column('comuna_codes', sa.JSON(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_senapred_active', 'senapred_alerts', ['is_active', 'level', 'senapred_issued_at'], unique=False)
    op.create_index(op.f('ix_senapred_alerts_parent_id'), 'senapred_alerts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_senapred_alerts_region_code'), 'senapred_alerts', ['region_code'], unique=False)
    op.create_index(op.f('ix_senapred_alerts_senapred_id'), 'senapred_alerts', ['senapred_id'], unique=True)
    op.create_index(op.f('ix_senapred_alerts_senapred_issued_at'), 'senapred_alerts', ['senapred_issued_at'], unique=False)
    op.create_index('ix_senapred_region_active', 'senapred_alerts', ['region_code', 'is_active', 'senapred_issued_at'], unique=False)
    op.create_table('simulacros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('drill_date', sa.Date(), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(length=128), nullable=True),
    sa.Column('drill_type', sa.String(length=64), nullable=False),
    sa.Column('participating_comunas', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail_url', sa.String(length=512), nullable=False),
    sa.Column('mensaje_sae', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulacros_date_region', 'simulacros', ['drill_date', 'region_code'], unique=False)
    op.create_index(op.f('ix_simulacros_drill_date'), 'simulacros', ['drill_date'], unique=False)
    op.create_index(op.f('ix_simulacros_region_code'), 'simulacros', ['region_code'], unique=False)
    op.create_index(op.f('ix_simulacros_slug'), 'simulacros', ['slug'], unique=True)
    op.create_index('ix_simulacros_type_date', 'simulacros', ['drill_type', 'drill_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('comunas',
    sa.Column('cod_comuna', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('codregion', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['codregion'], ['regions.codregion'], ),
    sa.PrimaryKeyConstraint('cod_comuna')
    )
    op.create_index(op.f('ix_comunas_codregion'), 'comunas', ['codregion'], unique=False)
    op.create_table('family_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('completion_pct', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_plans_user_id'), 'family_plans', ['user_id'], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id')
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_family_plans_user_id'), table_name='family_plans')
    op.drop_table('family_plans')
    op.drop_index(op.f('ix_comunas_codregion'), table_name='comunas')
    op.drop_table('comunas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_simulacros_type_date', table_name='simulacros')
    op.drop_index(op.f('ix_simulacros_slug'), table_name='simulacros')
    op.drop_index(op.f('ix_simulacros_region_code'), table_name='simulacros')
    op.drop_index(op.f('ix_simulacros_drill_date'), table_name='simulacros')
    op.drop_index('ix_simulacros_date_region', table_name='simulacros')
    op.drop_table('simulacros')
    op.drop_index('ix_senapred_region_active', table_name='senapred_alerts')
    op.drop_index(op.f('ix_senapred_alerts_senapred_issued_at'), table_name='senapred_alerts')
    op.drop_index(op.f('ix_senapred_alerts_senapred_id'), table_name='senapred_alerts')
    op.drop_index(op.f('ix_senapred_alerts_region_code'), table_name='senapred_alerts')
    op.drop_index(op.f('ix_senapred_alerts_parent_id'), table_name='senapred_alerts')
    op.drop_index('ix_senapred_active', table_name='senapred_alerts')
    op.drop_table('senapred_alerts')
    op.drop_index('idx_impact_event_comuna', table_name='seismic_impacts')
    op.drop_index('idx_impact_event', table_name='seismic_impacts')
    op.drop_index('idx_impact_comuna', table_name='seismic_impacts')
    op.drop_table('seismic_impacts')
    op.drop_index('idx_event_time', table_name='seismic_events')
    op.drop_index('idx_event_source', table_name='seismic_events')
    op.drop_table('seismic_events')
    op.drop_index(op.f('ix_risk_scores_cod_comuna'), table_name='risk_scores')
    op.drop_index('idx_risk_severity', table_name='risk_scores')
    op.drop_index('idx_risk_comuna_time', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('regions')
    op.drop_table('daily_risk_scores')
    op.drop_index('idx_climate_comuna_time', table_name='climate_readings')
    op.drop_table('climate_readings')
    # ### end Alembic commands ###
