"""sync_runs

Revision ID: e9f1289a62db
Revises: c5dffad43956
Create Date: 2026-07-13 02:25:59.946407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f1289a62db'
down_revision: Union[str, Sequence[str], None] = 'c5dffad43956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_written', sa.Integer(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_runs_job_finished', 'sync_runs', ['job_id', 'finished_at'], unique=False)
    op.create_index(op.f('ix_sync_runs_job_id'), 'sync_runs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_runs_job_id'), table_name='sync_runs')
    op.drop_index('ix_sync_runs_job_finished', table_name='sync_runs')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
