/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Credentials */
        post: operations["verify_credentials_api_v1_auth_verify_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oauth Google */
        post: operations["oauth_google_api_v1_auth_oauth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password Endpoint */
        post: operations["reset_password_endpoint_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get National Risk */
        get: operations["get_national_risk_api_v1_risk_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/comunas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Comuna Map Scores
         * @description Latest composite_score per comuna (alert evaluator input / tooling).
         *
         *     Not used for map choropleth — the monitor paints fills from active
         *     `alert_level`, not scores.
         */
        get: operations["get_comuna_map_scores_api_v1_risk_comunas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regiones/{codregion}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Risk
         * @description Detailed risk for one region + list of its comunas with scores.
         */
        get: operations["get_region_risk_api_v1_regiones__codregion__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunas/nearest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nearest Comuna
         * @description Resolve the closest comuna centroid to a GPS position.
         */
        get: operations["get_nearest_comuna_api_v1_comunas_nearest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunas/{cod_comuna}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comuna Risk */
        get: operations["get_comuna_risk_api_v1_comunas__cod_comuna__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Events
         * @description List seismic events for one calendar day (Chile timezone).
         */
        get: operations["list_recent_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Impact
         * @description Return estimated impact (risk score) on every comuna from one specific event.
         */
        get: operations["get_event_impact_api_v1_events__event_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active Alerts
         * @description Alertas activas: SERNAPRED + ChileRisk + SERNAGEOMIN + MeteoChile.
         */
        get: operations["list_active_alerts_api_v1_alerts_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/meteochile/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Meteochile Zone Geojson
         * @description GeoJSON de franjas DMC AAA activas (polígonos oficiales, no regiones CUT).
         */
        get: operations["list_meteochile_zone_geojson_api_v1_alerts_meteochile_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Dashboard Summary */
        get: operations["read_dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National Stats */
        get: operations["national_stats_api_v1_stats_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/regiones/{codregion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Region Stats */
        get: operations["region_stats_api_v1_stats_regiones__codregion__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_v1_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_v1_stats_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Family Plan */
        get: operations["read_family_plan_api_v1_family_plan_get"];
        /** Write Family Plan */
        put: operations["write_family_plan_api_v1_family_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulacros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Simulacros Endpoint
         * @description List SERNAPRED simulacros (drills) with optional filters.
         */
        get: operations["list_simulacros_endpoint_api_v1_simulacros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulacros/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Simulacro Endpoint */
        get: operations["next_simulacro_endpoint_api_v1_simulacros_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulacros/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simulacro Detail Endpoint */
        get: operations["simulacro_detail_endpoint_api_v1_simulacros__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/air-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Air Quality
         * @description List Aire Chile GEC zone conditions for a Chile calendar day.
         */
        get: operations["list_air_quality_api_v1_air_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/air-quality/by-comuna/{cod_comuna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Air Quality By Comuna
         * @description Lookup GEC condition for a CUT comuna (404 if not in a GEC zone).
         */
        get: operations["air_quality_by_comuna_api_v1_air_quality_by_comuna__cod_comuna__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/air-quality/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Air Quality Zone
         * @description Detail for one Aire Chile zone slug.
         */
        get: operations["air_quality_zone_api_v1_air_quality__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_v1_system_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chat Threads */
        get: operations["list_chat_threads_api_v1_chat_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat Thread */
        get: operations["get_chat_thread_api_v1_chat_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meeting-points/nearest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nearest Meeting Points */
        get: operations["nearest_meeting_points_api_v1_meeting_points_nearest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/disaster-guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Guides */
        get: operations["list_guides_api_v1_disaster_guides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disaster-guides/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guide Detail */
        get: operations["guide_detail_api_v1_disaster_guides__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveAlertOut */
        ActiveAlertOut: {
            /** Id */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "senapred" | "chilerisk" | "sernageomin" | "meteochile";
            /**
             * Level
             * @enum {string}
             */
            level: "preventiva" | "amarilla" | "naranja" | "roja" | "informativa";
            /** Category */
            category?: string | null;
            /** Title */
            title: string;
            /** Content */
            content?: string | null;
            /** Url Access */
            url_access?: string | null;
            /** External Url */
            external_url?: string | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
            /** Region Code */
            region_code?: number | null;
            /** Region Name */
            region_name?: string | null;
            /**
             * Affected Scope
             * @default unknown
             * @enum {string}
             */
            affected_scope: "region" | "comuna" | "unknown";
            /**
             * Comuna Codes
             * @default []
             */
            comuna_codes: number[];
            /**
             * Is Monitor
             * @default false
             */
            is_monitor: boolean;
            /** Parent Id */
            parent_id?: string | null;
            /** Thread Root Id */
            thread_root_id?: string | null;
            /**
             * Record Kind
             * @default alerta
             * @enum {string}
             */
            record_kind: "alerta" | "evento";
            /** Hazard Type */
            hazard_type?: string | null;
            /** Composite Score */
            composite_score?: number | null;
            /** Dominant Hazard */
            dominant_hazard?: string | null;
            /** Severity */
            severity?: string | null;
            /** Risk Detail */
            risk_detail?: string | null;
        };
        /** AirQualityListResponse */
        AirQualityListResponse: {
            /** Items */
            items: components["schemas"]["AirQualityZoneOut"][];
            /** Total */
            total: number;
            /**
             * Condition Date
             * Format: date
             */
            condition_date: string;
        };
        /** AirQualityZoneOut */
        AirQualityZoneOut: {
            /** Zone Slug */
            zone_slug: string;
            /**
             * Condition Date
             * Format: date
             */
            condition_date: string;
            /**
             * Level
             * @enum {string}
             */
            level: "bueno" | "regular" | "alerta" | "preemergencia" | "emergencia";
            /** Forecast Date */
            forecast_date?: string | null;
            /** Forecast Level */
            forecast_level?: ("bueno" | "regular" | "alerta" | "preemergencia" | "emergencia") | null;
            /** Pm25 Range Label */
            pm25_range_label?: string | null;
            /** Zone Name */
            zone_name: string;
            /** Region Code */
            region_code?: number | null;
            /** Comuna Codes */
            comuna_codes?: number[];
            /** Measures Current */
            measures_current?: string[];
            /** Restrictions Permanent */
            restrictions_permanent?: string[];
            /** External Url */
            external_url: string;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /** AuthUserOut */
        AuthUserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Home Comuna Code */
            home_comuna_code?: number | null;
        };
        /** ChatMessageIn */
        ChatMessageIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatMessageOut */
        ChatMessageOut: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Tool Trace */
            tool_trace?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessageIn"][];
            /** Thread Id */
            thread_id?: string | null;
            /** Comuna Code */
            comuna_code?: number | null;
            /** Region Code */
            region_code?: number | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Tool Calls Used */
            tool_calls_used?: components["schemas"]["ToolCallTrace"][];
            /** Sources */
            sources?: string[];
        };
        /** ChatThreadDetailOut */
        ChatThreadDetailOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["ChatMessageOut"][];
        };
        /** ChatThreadSummaryOut */
        ChatThreadSummaryOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** CompareOut */
        CompareOut: {
            /** Regiones */
            regiones: components["schemas"]["CompareRegionEntry"][];
        };
        /** CompareRegionEntry */
        CompareRegionEntry: {
            /** Codregion */
            codregion: number;
            /** Name */
            name: string;
            /** Composite Score */
            composite_score: number;
            /** Dominant Hazard */
            dominant_hazard: string;
            /** Severity */
            severity: string;
        };
        /** ComunaImpact */
        ComunaImpact: {
            /** Cod Comuna */
            cod_comuna: number;
            /** Name */
            name: string;
            /** Codregion */
            codregion: number;
            /** Distance Km */
            distance_km: number;
            /** Estimated Intensity */
            estimated_intensity: number;
            /** Risk Score */
            risk_score: number;
        };
        /** ComunaMapScore */
        ComunaMapScore: {
            /** Cod Comuna */
            cod_comuna: number;
            /** Composite Score */
            composite_score: number;
        };
        /** ComunaRiskDetail */
        ComunaRiskDetail: {
            /** Cod Comuna */
            cod_comuna: number;
            /** Name */
            name: string;
            /** Codregion */
            codregion: number;
            /** Sismo Score */
            sismo_score: number;
            /** Ola Calor Score */
            ola_calor_score: number;
            /** Ola Frio Score */
            ola_frio_score: number;
            /** Viento Score */
            viento_score: number;
            /** Inundacion Score */
            inundacion_score: number;
            /** Composite Score */
            composite_score: number;
            /** Dominant Hazard */
            dominant_hazard: string;
            /** Severity */
            severity: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Temperature C */
            temperature_c?: number | null;
            /** Wind Speed Kmh */
            wind_speed_kmh?: number | null;
            seismic_impact?: components["schemas"]["SeismicImpactDetail"] | null;
        };
        /** ContactIn */
        ContactIn: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Type
             * @default family
             */
            type: string;
        };
        /** DashboardSummaryOut */
        DashboardSummaryOut: {
            /** Summary */
            summary: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Cached */
            cached: boolean;
            /** Comuna Name */
            comuna_name?: string | null;
        };
        /** DisasterGuideListOut */
        DisasterGuideListOut: {
            /** Items */
            items: components["schemas"]["DisasterGuideOut"][];
        };
        /** DisasterGuideOut */
        DisasterGuideOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Antes */
            antes?: string[];
            /** Durante */
            durante?: string[];
            /** Despues */
            despues?: string[];
            /** App Path */
            app_path: string;
        };
        /** DrillEvaluationIn */
        DrillEvaluationIn: {
            /** Knew Route */
            knew_route?: boolean | null;
            /** Found Kit */
            found_kit?: boolean | null;
            /** Evacuated */
            evacuated?: boolean | null;
            /** Protected Pets */
            protected_pets?: boolean | null;
            /** Roles Worked */
            roles_worked?: boolean | null;
            /**
             * Improvements
             * @default
             */
            improvements: string;
        };
        /** DrillIn */
        DrillIn: {
            /** Id */
            id: string;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Emergency Type
             * @default
             */
            emergency_type: string;
            /**
             * Outcome
             * @default
             */
            outcome: string;
            /** Improvements */
            improvements?: string[];
            evaluation?: components["schemas"]["DrillEvaluationIn"];
        };
        /** EmergencyKitIn */
        EmergencyKitIn: {
            /** Base */
            base?: {
                [key: string]: boolean;
            };
            /** Infant */
            infant?: {
                [key: string]: boolean;
            };
            /** Pregnant */
            pregnant?: {
                [key: string]: boolean;
            };
            /** Tea */
            tea?: {
                [key: string]: boolean;
            };
            /** Pets */
            pets?: {
                [key: string]: boolean;
            };
        };
        /** FamilyMemberIn */
        FamilyMemberIn: {
            /** Id */
            id: string;
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /**
             * Document
             * @default
             */
            document: string;
            /**
             * Sex
             * @default
             */
            sex: string;
            /** Age */
            age?: number | null;
            /**
             * Nationality
             * @default
             */
            nationality: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Medical Conditions
             * @default
             */
            medical_conditions: string;
            /**
             * Contraindications
             * @default
             */
            contraindications: string;
            /**
             * Special Needs
             * @default
             */
            special_needs: string;
            /** Flags */
            flags?: string[];
        };
        /** FamilyPlanDataIn */
        FamilyPlanDataIn: {
            /** Members */
            members?: components["schemas"]["FamilyMemberIn"][];
            /** Pets */
            pets?: components["schemas"]["PetIn"][];
            /** Threats */
            threats?: components["schemas"]["ThreatIn"][];
            /** Safe Zones */
            safe_zones?: components["schemas"]["SafeZoneIn"][];
            floor_map?: components["schemas"]["FloorMapIn"];
            /** Roles */
            roles?: components["schemas"]["RoleAssignmentIn"][];
            /** Contacts */
            contacts?: components["schemas"]["ContactIn"][];
            emergency_kit?: components["schemas"]["EmergencyKitIn"];
            /** Drills */
            drills?: components["schemas"]["DrillIn"][];
        };
        /** FamilyPlanOut */
        FamilyPlanOut: {
            /** Id */
            id?: string | null;
            data: components["schemas"]["FamilyPlanDataIn"];
            /**
             * Completion Pct
             * @default 0
             */
            completion_pct: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** FamilyPlanUpsertRequest */
        FamilyPlanUpsertRequest: {
            data: components["schemas"]["FamilyPlanDataIn"];
        };
        /** FloorMapIn */
        FloorMapIn: {
            /** Rooms */
            rooms?: components["schemas"]["FloorMapRoomIn"][];
            /** Markers */
            markers?: components["schemas"]["FloorMapMarkerIn"][];
            /** Routes */
            routes?: components["schemas"]["FloorMapRouteIn"][];
            /** Zones */
            zones?: components["schemas"]["FloorMapZoneIn"][];
            /**
             * Active Layer
             * @default safe
             */
            active_layer: string;
            /** Saved At */
            saved_at?: string | null;
        };
        /** FloorMapMarkerIn */
        FloorMapMarkerIn: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /** FloorMapPointIn */
        FloorMapPointIn: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /** FloorMapRoomIn */
        FloorMapRoomIn: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * W
             * @default 80
             */
            w: number;
            /**
             * H
             * @default 60
             */
            h: number;
        };
        /** FloorMapRouteIn */
        FloorMapRouteIn: {
            /** Id */
            id: string;
            /** Points */
            points?: components["schemas"]["FloorMapPointIn"][];
        };
        /** FloorMapZoneIn */
        FloorMapZoneIn: {
            /** Id */
            id: string;
            /**
             * Type
             * @default safe
             */
            type: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * W
             * @default 60
             */
            w: number;
            /**
             * H
             * @default 60
             */
            h: number;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** GoogleOAuthRequest */
        GoogleOAuthRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Provider Account Id */
            provider_account_id: string;
            /** Google Id Token */
            google_id_token?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeetingPointNearestResponse */
        MeetingPointNearestResponse: {
            /** Items */
            items: components["schemas"]["MeetingPointOut"][];
            /** Origin Lat */
            origin_lat: number;
            /** Origin Lon */
            origin_lon: number;
            /** Hazard */
            hazard?: string | null;
            /**
             * Total Candidates
             * @default 0
             */
            total_candidates: number;
        };
        /** MeetingPointOut */
        MeetingPointOut: {
            /** Id */
            id: string;
            /** Hazard */
            hazard: string;
            /** Comuna */
            comuna: string;
            /** Provincia */
            provincia: string;
            /** Region */
            region: string;
            /** Sector */
            sector: string;
            /** Lng */
            lng: number;
            /** Lat */
            lat: number;
            /** Distance Km */
            distance_km?: number | null;
        };
        /** NationalAvgScores */
        NationalAvgScores: {
            /** Composite Score */
            composite_score: number;
            /** Sismo */
            sismo: number;
            /** Ola Calor */
            ola_calor: number;
            /** Ola Frio */
            ola_frio: number;
            /** Viento */
            viento: number;
        };
        /** NationalRiskEntry */
        NationalRiskEntry: {
            /** Codregion */
            codregion: number;
            /** Name */
            name: string;
            /** Composite Score */
            composite_score: number;
            /** Dominant Hazard */
            dominant_hazard: string;
            /** Severity */
            severity: string;
            /** Sismo Score */
            sismo_score: number;
            /** Ola Calor Score */
            ola_calor_score: number;
            /** Ola Frio Score */
            ola_frio_score: number;
            /** Viento Score */
            viento_score: number;
            /** Comuna Count */
            comuna_count: number;
        };
        /** NationalStatsOut */
        NationalStatsOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            national_avg: components["schemas"]["NationalAvgScores"];
            severity_distribution: components["schemas"]["SeverityDistribution"];
            /** Top Regions */
            top_regions: components["schemas"]["RegionRankEntry"][];
            /** Bottom Regions */
            bottom_regions: components["schemas"]["RegionRankEntry"][];
        };
        /** NearestComunaOut */
        NearestComunaOut: {
            /** Cod Comuna */
            cod_comuna: number;
            /** Name */
            name: string;
            /** Codregion */
            codregion: number;
            /** Distance Km */
            distance_km: number;
            /** Origin Lat */
            origin_lat: number;
            /** Origin Lon */
            origin_lon: number;
        };
        /** PetIn */
        PetIn: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Species
             * @default
             */
            species: string;
            /** Age */
            age?: number | null;
            /**
             * Characteristics
             * @default
             */
            characteristics: string;
            /**
             * Special Needs
             * @default
             */
            special_needs: string;
        };
        /** RegionAvgScores */
        RegionAvgScores: {
            /** Composite */
            composite: number;
            /** Sismo */
            sismo: number;
            /** Ola Calor */
            ola_calor: number;
            /** Ola Frio */
            ola_frio: number;
            /** Viento */
            viento: number;
        };
        /** RegionComunaScore */
        RegionComunaScore: {
            /** Cod Comuna */
            cod_comuna: number;
            /** Sismo Score */
            sismo_score: number;
            /** Ola Calor Score */
            ola_calor_score: number;
            /** Ola Frio Score */
            ola_frio_score: number;
            /** Viento Score */
            viento_score: number;
            /** Inundacion Score */
            inundacion_score: number;
            /** Composite Score */
            composite_score: number;
            /** Dominant Hazard */
            dominant_hazard: string;
            /** Severity */
            severity: string;
        };
        /** RegionExtremeScores */
        RegionExtremeScores: {
            /** Composite */
            composite: number;
            /** Comuna Name */
            comuna_name: string;
        };
        /** RegionRankEntry */
        RegionRankEntry: {
            /** Codregion */
            codregion: number;
            /** Name */
            name: string;
            /** Composite Score */
            composite_score: number;
        };
        /** RegionRiskDetailResponse */
        RegionRiskDetailResponse: {
            /** Codregion */
            codregion: number;
            /** Name */
            name: string;
            /**
             * Risk Computed At
             * Format: date-time
             */
            risk_computed_at: string;
            /** Sismo Score */
            sismo_score: number;
            /** Ola Calor Score */
            ola_calor_score: number;
            /** Ola Frio Score */
            ola_frio_score: number;
            /** Viento Score */
            viento_score: number;
            /** Inundacion Score */
            inundacion_score: number;
            /** Composite Score */
            composite_score: number;
            /** Dominant Hazard */
            dominant_hazard: string;
            /** Severity */
            severity: string;
            /** Comuna Count */
            comuna_count: number;
            /** Avg Temperature C */
            avg_temperature_c?: number | null;
            /** Avg Wind Speed Kmh */
            avg_wind_speed_kmh?: number | null;
            /** Comunas */
            comunas: components["schemas"]["RegionComunaScore"][];
        };
        /** RegionStatsOut */
        RegionStatsOut: {
            /** Codregion */
            codregion: number;
            /** Name */
            name: string;
            /** Comuna Count */
            comuna_count: number;
            avg_scores: components["schemas"]["RegionAvgScores"];
            max_scores: components["schemas"]["RegionExtremeScores"];
            min_scores: components["schemas"]["RegionExtremeScores"];
            /** Dominant Hazard */
            dominant_hazard: string;
            severity_breakdown: components["schemas"]["SeverityDistribution"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** RoleAssignmentIn */
        RoleAssignmentIn: {
            /** Task */
            task: string;
            /** Member Id */
            member_id?: string | null;
        };
        /** SafeZoneIn */
        SafeZoneIn: {
            /** Emergency */
            emergency: string;
            /**
             * Safe Place
             * @default
             */
            safe_place: string;
            /**
             * Evacuation Route
             * @default
             */
            evacuation_route: string;
            /**
             * Safe Zone
             * @default
             */
            safe_zone: string;
            /**
             * Meeting Point
             * @default
             */
            meeting_point: string;
        };
        /** SeismicEventResponse */
        SeismicEventResponse: {
            /** Id */
            id: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Magnitude */
            magnitude: number;
            /** Depth Km */
            depth_km: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Occurred At Local */
            occurred_at_local?: string | null;
            /** Source */
            source: string;
            /** Detail Url */
            detail_url?: string | null;
            /**
             * Is Perceived
             * @default false
             */
            is_perceived: boolean;
            /** Intensity Report Url */
            intensity_report_url?: string | null;
            /** Reported Intensity Max */
            reported_intensity_max?: number | null;
            /** Related Senapred Events */
            related_senapred_events?: components["schemas"]["SenapredAlertBrief"][];
            /** Related Senapred Alerts */
            related_senapred_alerts?: components["schemas"]["SenapredAlertBrief"][];
            /** Raw Data */
            raw_data?: {
                [key: string]: unknown;
            } | null;
        };
        /** SeismicImpactDetail */
        SeismicImpactDetail: {
            /** Event Id */
            event_id: number;
            /** Distance Km */
            distance_km: number;
            /** Estimated Intensity */
            estimated_intensity: number;
            /** Risk Score */
            risk_score: number;
            /** Magnitude */
            magnitude: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Detail Url */
            detail_url?: string | null;
        };
        /** SeismicImpactResponse */
        SeismicImpactResponse: {
            event: components["schemas"]["SeismicEventResponse"];
            /** Affected Comunas */
            affected_comunas: components["schemas"]["ComunaImpact"][];
            /** Total Affected */
            total_affected: number;
        };
        /** SenapredAlertBrief */
        SenapredAlertBrief: {
            /** Id */
            id: string;
            /**
             * Record Kind
             * @enum {string}
             */
            record_kind: "alerta" | "evento";
            /** Title */
            title: string;
            /**
             * Level
             * @enum {string}
             */
            level: "preventiva" | "amarilla" | "naranja" | "roja" | "informativa";
            /** External Url */
            external_url?: string | null;
            /** Hazard Type */
            hazard_type?: string | null;
        };
        /** SeverityDistribution */
        SeverityDistribution: {
            /** Bajo */
            bajo: number;
            /** Moderado */
            moderado: number;
            /** Alto */
            alto: number;
            /** Critico */
            critico: number;
        };
        /** SimulacroBodyBlock */
        SimulacroBodyBlock: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "heading" | "paragraph" | "steps" | "link_list" | "sae_notice" | "callout";
            /** Title */
            title?: string | null;
            /** Text */
            text?: string | null;
            /** Items */
            items?: string[];
            /** Links */
            links?: components["schemas"]["SimulacroBodyLink"][];
        };
        /** SimulacroBodyLink */
        SimulacroBodyLink: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** SimulacroDetailOut */
        SimulacroDetailOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Drill Date
             * Format: date
             */
            drill_date: string;
            /** Region Code */
            region_code?: number | null;
            /** Region Name */
            region_name?: string | null;
            /**
             * Drill Type
             * @default otro
             * @enum {string}
             */
            drill_type: "sismo_tsunami_borde_costero" | "sismo_tsunami_educacion" | "erupcion_volcanica" | "remocion_en_masa" | "otro";
            /**
             * Participating Comunas
             * @default []
             */
            participating_comunas: string[];
            /** Summary */
            summary?: string | null;
            /** Detail Url */
            detail_url: string;
            /**
             * Mensaje Sae
             * @default false
             */
            mensaje_sae: boolean;
            /**
             * Source
             * @default future
             * @enum {string}
             */
            source: "future" | "recent" | "archive";
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
            /** Headline */
            headline?: string | null;
            /** Schedule Note */
            schedule_note?: string | null;
            /** Hero Image Url */
            hero_image_url?: string | null;
            /** Body Blocks */
            body_blocks?: components["schemas"]["SimulacroBodyBlock"][];
        };
        /** SimulacroListResponse */
        SimulacroListResponse: {
            /** Items */
            items: components["schemas"]["SimulacroOut"][];
            /** Total */
            total: number;
            /** Next Synced At */
            next_synced_at?: string | null;
        };
        /** SimulacroOut */
        SimulacroOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Drill Date
             * Format: date
             */
            drill_date: string;
            /** Region Code */
            region_code?: number | null;
            /** Region Name */
            region_name?: string | null;
            /**
             * Drill Type
             * @default otro
             * @enum {string}
             */
            drill_type: "sismo_tsunami_borde_costero" | "sismo_tsunami_educacion" | "erupcion_volcanica" | "remocion_en_masa" | "otro";
            /**
             * Participating Comunas
             * @default []
             */
            participating_comunas: string[];
            /** Summary */
            summary?: string | null;
            /** Detail Url */
            detail_url: string;
            /**
             * Mensaje Sae
             * @default false
             */
            mensaje_sae: boolean;
            /**
             * Source
             * @default future
             * @enum {string}
             */
            source: "future" | "recent" | "archive";
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Job Id */
            job_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Items Written */
            items_written: number;
            /** Error Text */
            error_text?: string | null;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Runs */
            runs: components["schemas"]["SyncRunOut"][];
        };
        /** ThreatIn */
        ThreatIn: {
            /** Id */
            id: string;
            /** Risk */
            risk: string;
            /**
             * Category
             * @default internal
             */
            category: string;
            /**
             * Probability
             * @default 1
             */
            probability: number;
            /**
             * Impact
             * @default 1
             */
            impact: number;
            /**
             * Corrective Action
             * @default
             */
            corrective_action: string;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
        };
        /** ToolCallTrace */
        ToolCallTrace: {
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** TrendsOut */
        TrendsOut: {
            period: components["schemas"]["TrendsPeriod"];
            /** Message */
            message: string;
        };
        /** TrendsPeriod */
        TrendsPeriod: {
            /** Start */
            start: string;
            /** End */
            end: string;
        };
        /** UserProfileOut */
        UserProfileOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Home Comuna Code */
            home_comuna_code?: number | null;
            /** Home Comuna Name */
            home_comuna_name?: string | null;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            /** Home Comuna Code */
            home_comuna_code?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyCredentialsRequest */
        VerifyCredentialsRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_credentials_api_v1_auth_verify_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_api_v1_auth_oauth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleOAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_endpoint_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_national_risk_api_v1_risk_national_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalRiskEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comuna_map_scores_api_v1_risk_comunas_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunaMapScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_risk_api_v1_regiones__codregion__risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codregion: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionRiskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nearest_comuna_api_v1_comunas_nearest_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearestComunaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comuna_risk_api_v1_comunas__cod_comuna__risk_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile para impacto sísmico en popup (YYYY-MM-DD). */
                date?: string | null;
            };
            header?: never;
            path: {
                cod_comuna: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunaRiskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeismicEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_impact_api_v1_events__event_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeismicImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_alerts_api_v1_alerts_active_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
                /** @description codregion (1-16) */
                region?: number | null;
                /** @description cod_comuna: filtra por alcance comunal/regional */
                comuna?: number | null;
                /** @description Filtrar por nivel */
                level?: ("preventiva" | "amarilla" | "naranja" | "roja" | "informativa") | null;
                /** @description alerta (ATP) | evento (Sismos y otros) */
                kind?: ("alerta" | "evento") | null;
                /** @description sismo | volcan | incendio | incendio_estructural | remocion | otros */
                hazard?: ("sismo" | "volcan" | "incendio" | "incendio_estructural" | "remocion" | "otros") | null;
                /** @description Si true, incluye HTML/texto `content` (~MB). El monitor solo necesita metadatos; default false. */
                include_content?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meteochile_zone_geojson_api_v1_alerts_meteochile_zones_get: {
        parameters: {
            query?: {
                /** @description Solo disponible para hoy (franjas DMC vigentes). */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryOut"];
                };
            };
        };
    };
    national_stats_api_v1_stats_national_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalStatsOut"];
                };
            };
        };
    };
    region_stats_api_v1_stats_regiones__codregion__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codregion: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_v1_stats_trends_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_stats_compare_get: {
        parameters: {
            query: {
                /** @description Comma-separated region codes (max 8) */
                codregions: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_family_plan_api_v1_family_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyPlanOut"];
                };
            };
        };
    };
    write_family_plan_api_v1_family_plan_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyPlanUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulacros_endpoint_api_v1_simulacros_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                /** @description codregion (1-16) */
                region?: number | null;
                type?: ("sismo_tsunami_borde_costero" | "sismo_tsunami_educacion" | "erupcion_volcanica" | "remocion_en_masa" | "otro") | null;
                /** @description future | recent | archive */
                source?: ("future" | "recent" | "archive") | null;
                upcoming_only?: boolean;
                past_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulacroListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_simulacro_endpoint_api_v1_simulacros_next_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulacroOut"] | null;
                };
            };
        };
    };
    simulacro_detail_endpoint_api_v1_simulacros__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulacroDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_air_quality_api_v1_air_quality_get: {
        parameters: {
            query?: {
                date?: string | null;
                region?: number | null;
                /** @description If true, only zones with level ≥ alerta */
                episode_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    air_quality_by_comuna_api_v1_air_quality_by_comuna__cod_comuna__get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path: {
                cod_comuna: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityZoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    air_quality_zone_api_v1_air_quality__slug__get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityZoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_v1_system_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_threads_api_v1_chat_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadSummaryOut"][];
                };
            };
        };
    };
    get_chat_thread_api_v1_chat_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nearest_meeting_points_api_v1_meeting_points_nearest_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                hazard?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingPointNearestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
        };
    };
    patch_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_guides_api_v1_disaster_guides_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisasterGuideListOut"];
                };
            };
        };
    };
    guide_detail_api_v1_disaster_guides__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisasterGuideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
