/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Credentials */
        post: operations["verify_credentials_api_v1_auth_verify_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oauth Google */
        post: operations["oauth_google_api_v1_auth_oauth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password Endpoint */
        post: operations["reset_password_endpoint_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get National Risk */
        get: operations["get_national_risk_api_v1_risk_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/comunas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Comuna Map Scores
         * @description Lightweight scores for map coloring (composite_score per comuna).
         */
        get: operations["get_comuna_map_scores_api_v1_risk_comunas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regiones/{codregion}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Risk
         * @description Detailed risk for one region + list of its comunas with scores.
         */
        get: operations["get_region_risk_api_v1_regiones__codregion__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunas/{cod_comuna}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comuna Risk */
        get: operations["get_comuna_risk_api_v1_comunas__cod_comuna__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Events
         * @description List seismic events for one calendar day (Chile timezone).
         */
        get: operations["list_recent_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Impact
         * @description Return estimated impact (risk score) on every comuna from one specific event.
         */
        get: operations["get_event_impact_api_v1_events__event_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active Alerts
         * @description Alertas activas: SERNAPRED (alertas + eventos) + ChileRisk.
         */
        get: operations["list_active_alerts_api_v1_alerts_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National Stats */
        get: operations["national_stats_api_v1_stats_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/regiones/{codregion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Region Stats */
        get: operations["region_stats_api_v1_stats_regiones__codregion__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_v1_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_v1_stats_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Family Plan */
        get: operations["read_family_plan_api_v1_family_plan_get"];
        /** Write Family Plan */
        put: operations["write_family_plan_api_v1_family_plan_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulacros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Simulacros Endpoint
         * @description List SERNAPRED simulacros (drills) with optional filters.
         */
        get: operations["list_simulacros_endpoint_api_v1_simulacros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/air-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Air Quality
         * @description List Aire Chile GEC zone conditions for a Chile calendar day.
         */
        get: operations["list_air_quality_api_v1_air_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/air-quality/by-comuna/{cod_comuna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Air Quality By Comuna
         * @description Lookup GEC condition for a CUT comuna (404 if not in a GEC zone).
         */
        get: operations["air_quality_by_comuna_api_v1_air_quality_by_comuna__cod_comuna__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/air-quality/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Air Quality Zone
         * @description Detail for one Aire Chile zone slug.
         */
        get: operations["air_quality_zone_api_v1_air_quality__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_v1_system_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveAlertOut */
        ActiveAlertOut: {
            /** Id */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "senapred" | "chilerisk";
            /**
             * Level
             * @enum {string}
             */
            level: "preventiva" | "amarilla" | "naranja" | "roja" | "informativa";
            /** Category */
            category?: string | null;
            /** Title */
            title: string;
            /** Content */
            content?: string | null;
            /** Url Access */
            url_access?: string | null;
            /** External Url */
            external_url?: string | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
            /** Region Code */
            region_code?: number | null;
            /** Region Name */
            region_name?: string | null;
            /**
             * Affected Scope
             * @default unknown
             * @enum {string}
             */
            affected_scope: "region" | "comuna" | "unknown";
            /**
             * Comuna Codes
             * @default []
             */
            comuna_codes: number[];
            /**
             * Is Monitor
             * @default false
             */
            is_monitor: boolean;
            /** Parent Id */
            parent_id?: string | null;
            /** Thread Root Id */
            thread_root_id?: string | null;
            /**
             * Record Kind
             * @default alerta
             * @enum {string}
             */
            record_kind: "alerta" | "evento";
            /** Hazard Type */
            hazard_type?: string | null;
            /** Composite Score */
            composite_score?: number | null;
            /** Dominant Hazard */
            dominant_hazard?: string | null;
            /** Severity */
            severity?: string | null;
            /** Risk Detail */
            risk_detail?: string | null;
        };
        /** AirQualityListResponse */
        AirQualityListResponse: {
            /** Items */
            items: components["schemas"]["AirQualityZoneOut"][];
            /** Total */
            total: number;
            /**
             * Condition Date
             * Format: date
             */
            condition_date: string;
        };
        /** AirQualityZoneOut */
        AirQualityZoneOut: {
            /** Zone Slug */
            zone_slug: string;
            /**
             * Condition Date
             * Format: date
             */
            condition_date: string;
            /**
             * Level
             * @enum {string}
             */
            level: "bueno" | "regular" | "alerta" | "preemergencia" | "emergencia";
            /** Forecast Date */
            forecast_date?: string | null;
            /** Forecast Level */
            forecast_level?: ("bueno" | "regular" | "alerta" | "preemergencia" | "emergencia") | null;
            /** Pm25 Range Label */
            pm25_range_label?: string | null;
            /** Zone Name */
            zone_name: string;
            /** Region Code */
            region_code?: number | null;
            /** Comuna Codes */
            comuna_codes?: number[];
            /** Measures Current */
            measures_current?: string[];
            /** Restrictions Permanent */
            restrictions_permanent?: string[];
            /** External Url */
            external_url: string;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /** AuthUserOut */
        AuthUserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
        };
        /** ComunaMapScore */
        ComunaMapScore: {
            /** Cod Comuna */
            cod_comuna: number;
            /** Composite Score */
            composite_score: number;
        };
        /** ContactIn */
        ContactIn: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Type
             * @default family
             */
            type: string;
        };
        /** DrillEvaluationIn */
        DrillEvaluationIn: {
            /** Knew Route */
            knew_route?: boolean | null;
            /** Found Kit */
            found_kit?: boolean | null;
            /** Evacuated */
            evacuated?: boolean | null;
            /** Protected Pets */
            protected_pets?: boolean | null;
            /** Roles Worked */
            roles_worked?: boolean | null;
            /**
             * Improvements
             * @default
             */
            improvements: string;
        };
        /** DrillIn */
        DrillIn: {
            /** Id */
            id: string;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Emergency Type
             * @default
             */
            emergency_type: string;
            /**
             * Outcome
             * @default
             */
            outcome: string;
            /** Improvements */
            improvements?: string[];
            evaluation?: components["schemas"]["DrillEvaluationIn"];
        };
        /** EmergencyKitIn */
        EmergencyKitIn: {
            /** Base */
            base?: {
                [key: string]: boolean;
            };
            /** Infant */
            infant?: {
                [key: string]: boolean;
            };
            /** Pregnant */
            pregnant?: {
                [key: string]: boolean;
            };
            /** Tea */
            tea?: {
                [key: string]: boolean;
            };
            /** Pets */
            pets?: {
                [key: string]: boolean;
            };
        };
        /** FamilyMemberIn */
        FamilyMemberIn: {
            /** Id */
            id: string;
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /**
             * Document
             * @default
             */
            document: string;
            /**
             * Sex
             * @default
             */
            sex: string;
            /** Age */
            age?: number | null;
            /**
             * Nationality
             * @default
             */
            nationality: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Medical Conditions
             * @default
             */
            medical_conditions: string;
            /**
             * Contraindications
             * @default
             */
            contraindications: string;
            /**
             * Special Needs
             * @default
             */
            special_needs: string;
            /** Flags */
            flags?: string[];
        };
        /** FamilyPlanDataIn */
        FamilyPlanDataIn: {
            /** Members */
            members?: components["schemas"]["FamilyMemberIn"][];
            /** Pets */
            pets?: components["schemas"]["PetIn"][];
            /** Threats */
            threats?: components["schemas"]["ThreatIn"][];
            /** Safe Zones */
            safe_zones?: components["schemas"]["SafeZoneIn"][];
            floor_map?: components["schemas"]["FloorMapIn"];
            /** Roles */
            roles?: components["schemas"]["RoleAssignmentIn"][];
            /** Contacts */
            contacts?: components["schemas"]["ContactIn"][];
            emergency_kit?: components["schemas"]["EmergencyKitIn"];
            /** Drills */
            drills?: components["schemas"]["DrillIn"][];
        };
        /** FamilyPlanOut */
        FamilyPlanOut: {
            /** Id */
            id?: string | null;
            data: components["schemas"]["FamilyPlanDataIn"];
            /**
             * Completion Pct
             * @default 0
             */
            completion_pct: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** FamilyPlanUpsertRequest */
        FamilyPlanUpsertRequest: {
            data: components["schemas"]["FamilyPlanDataIn"];
        };
        /** FloorMapIn */
        FloorMapIn: {
            /** Rooms */
            rooms?: components["schemas"]["FloorMapRoomIn"][];
            /** Markers */
            markers?: components["schemas"]["FloorMapMarkerIn"][];
            /** Routes */
            routes?: components["schemas"]["FloorMapRouteIn"][];
            /** Zones */
            zones?: components["schemas"]["FloorMapZoneIn"][];
            /**
             * Active Layer
             * @default safe
             */
            active_layer: string;
            /** Saved At */
            saved_at?: string | null;
        };
        /** FloorMapMarkerIn */
        FloorMapMarkerIn: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /** FloorMapPointIn */
        FloorMapPointIn: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /** FloorMapRoomIn */
        FloorMapRoomIn: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * W
             * @default 80
             */
            w: number;
            /**
             * H
             * @default 60
             */
            h: number;
        };
        /** FloorMapRouteIn */
        FloorMapRouteIn: {
            /** Id */
            id: string;
            /** Points */
            points?: components["schemas"]["FloorMapPointIn"][];
        };
        /** FloorMapZoneIn */
        FloorMapZoneIn: {
            /** Id */
            id: string;
            /**
             * Type
             * @default safe
             */
            type: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * W
             * @default 60
             */
            w: number;
            /**
             * H
             * @default 60
             */
            h: number;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** GoogleOAuthRequest */
        GoogleOAuthRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Provider Account Id */
            provider_account_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PetIn */
        PetIn: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Species
             * @default
             */
            species: string;
            /** Age */
            age?: number | null;
            /**
             * Characteristics
             * @default
             */
            characteristics: string;
            /**
             * Special Needs
             * @default
             */
            special_needs: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** RoleAssignmentIn */
        RoleAssignmentIn: {
            /** Task */
            task: string;
            /** Member Id */
            member_id?: string | null;
        };
        /** SafeZoneIn */
        SafeZoneIn: {
            /** Emergency */
            emergency: string;
            /**
             * Safe Place
             * @default
             */
            safe_place: string;
            /**
             * Evacuation Route
             * @default
             */
            evacuation_route: string;
            /**
             * Safe Zone
             * @default
             */
            safe_zone: string;
            /**
             * Meeting Point
             * @default
             */
            meeting_point: string;
        };
        /** SimulacroListResponse */
        SimulacroListResponse: {
            /** Items */
            items: components["schemas"]["SimulacroOut"][];
            /** Total */
            total: number;
            /** Next Synced At */
            next_synced_at?: string | null;
        };
        /** SimulacroOut */
        SimulacroOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Drill Date
             * Format: date
             */
            drill_date: string;
            /** Region Code */
            region_code?: number | null;
            /** Region Name */
            region_name?: string | null;
            /**
             * Drill Type
             * @default otro
             * @enum {string}
             */
            drill_type: "sismo_tsunami_borde_costero" | "sismo_tsunami_educacion" | "erupcion_volcanica" | "remocion_en_masa" | "otro";
            /**
             * Participating Comunas
             * @default []
             */
            participating_comunas: string[];
            /** Summary */
            summary?: string | null;
            /** Detail Url */
            detail_url: string;
            /**
             * Mensaje Sae
             * @default false
             */
            mensaje_sae: boolean;
            /**
             * Source
             * @default future
             * @enum {string}
             */
            source: "future" | "recent" | "archive";
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Job Id */
            job_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Items Written */
            items_written: number;
            /** Error Text */
            error_text?: string | null;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Runs */
            runs: components["schemas"]["SyncRunOut"][];
        };
        /** ThreatIn */
        ThreatIn: {
            /** Id */
            id: string;
            /** Risk */
            risk: string;
            /**
             * Category
             * @default internal
             */
            category: string;
            /**
             * Probability
             * @default 1
             */
            probability: number;
            /**
             * Impact
             * @default 1
             */
            impact: number;
            /**
             * Corrective Action
             * @default
             */
            corrective_action: string;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyCredentialsRequest */
        VerifyCredentialsRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_credentials_api_v1_auth_verify_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_api_v1_auth_oauth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleOAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_endpoint_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_national_risk_api_v1_risk_national_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comuna_map_scores_api_v1_risk_comunas_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunaMapScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_risk_api_v1_regiones__codregion__risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codregion: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comuna_risk_api_v1_comunas__cod_comuna__risk_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile para impacto sísmico en popup (YYYY-MM-DD). */
                date?: string | null;
            };
            header?: never;
            path: {
                cod_comuna: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_impact_api_v1_events__event_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_alerts_api_v1_alerts_active_get: {
        parameters: {
            query?: {
                /** @description Día calendario Chile (YYYY-MM-DD). Por defecto: hoy. */
                date?: string | null;
                /** @description codregion (1-16) */
                region?: number | null;
                /** @description cod_comuna: filtra por alcance comunal/regional */
                comuna?: number | null;
                /** @description Filtrar por nivel */
                level?: ("preventiva" | "amarilla" | "naranja" | "roja" | "informativa") | null;
                /** @description alerta (ATP) | evento (Sismos y otros) */
                kind?: ("alerta" | "evento") | null;
                /** @description sismo | volcan | incendio | incendio_estructural | remocion | otros */
                hazard?: ("sismo" | "volcan" | "incendio" | "incendio_estructural" | "remocion" | "otros") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    national_stats_api_v1_stats_national_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    region_stats_api_v1_stats_regiones__codregion__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codregion: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_v1_stats_trends_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_stats_compare_get: {
        parameters: {
            query: {
                /** @description Comma-separated region codes */
                codregions: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_family_plan_api_v1_family_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyPlanOut"];
                };
            };
        };
    };
    write_family_plan_api_v1_family_plan_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyPlanUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulacros_endpoint_api_v1_simulacros_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                /** @description codregion (1-16) */
                region?: number | null;
                type?: ("sismo_tsunami_borde_costero" | "sismo_tsunami_educacion" | "erupcion_volcanica" | "remocion_en_masa" | "otro") | null;
                /** @description future | recent | archive */
                source?: ("future" | "recent" | "archive") | null;
                upcoming_only?: boolean;
                past_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulacroListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_air_quality_api_v1_air_quality_get: {
        parameters: {
            query?: {
                date?: string | null;
                region?: number | null;
                /** @description If true, only zones with level ≥ alerta */
                episode_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    air_quality_by_comuna_api_v1_air_quality_by_comuna__cod_comuna__get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path: {
                cod_comuna: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityZoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    air_quality_zone_api_v1_air_quality__slug__get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityZoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_v1_system_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
