export {
  ALERT_LEVEL_META,
  ALERT_SOURCE_META,
  CHILERISK_SEVERITY_META,
  formatChileRiskAlertHeadline,
  formatChileRiskAlertMainText,
  formatChileRiskAlertSummary,
  getActiveAlertMainText,
  getChileRiskRiskDetail,
  formatHazardLabel,
  getChileRiskAlertTitle,
  resolveChileRiskSeverity,
  POPUP_MAX_ALERTS,
  POPUP_MAX_SEISMIC,
  filterAlertsForRegion,
  formatAlertCategory,
  normalizeActiveAlert,
  normalizeActiveAlerts,
  shortenRegionName,
  sortActiveAlerts,
  sortSenapredAlerts,
  timeAgo,
} from "./alerts-display"